BOTS_DIRECTORY = "/bots"
REPLAYS_DIRECTORY = "/replays"
MATCHES_FILE = "matches"
RESULTS_FILE = "results.json"
RUN_TYPE = "local"
REALTIME = false
MAX_GAME_TIME = 80640
BOT_CONT_1_HOST = "127.0.0.1"
BOT_CONT_1_PORT = 8081
BOT_CONT_2_HOST = "127.0.0.1"
BOT_CONT_2_PORT = 8082
SC2_CONT_HOST = "127.0.0.1"
SC2_CONT_PORT = 8083
